//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Contacts = new HashSet<Contact>();
        }
        
        public int PersonId { get; set; }
        [Required]
        [Display(Name = "First  Name")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name = "Middle Name")]
        public string MiddleName { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Date of Birth")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string AddedBy { get; set; }
        [Required]
        [Display(Name = "Home Address")]
        public string HomeAddress { get; set; }
        [Required]
        [Display(Name = "Home City")]
        public string HomeCity { get; set; }
        [EmailAddress]
        [Display(Name = "FaceBook Account")]
        public string FaceBookAccountId { get; set; }
        [Display(Name = "LinkedIn Account")]
        [EmailAddress]
        public string LinkedInId { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string ImagePath { get; set; }
        [EmailAddress]
        [Display(Name = "Twitter Account")]
        public string TwitterId { get; set; }
        [Display(Name = "Email Account")]
        [EmailAddress]
        public string EmailId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
